language: node_js
node_js:
  - "6"
  - "7"
  - "8"
before_install:
  - wget http://git.savannah.gnu.org/cgit/parallel.git/plain/src/parallel # Minimal installation
  - chmod 755 parallel
  - cp parallel sem
  - sudo mv parallel sem /bin

script:
  - npm run build
  - npm run build:examples
  - npm run test:nocompile # already run schema and tsc in build
  - npm run check:schema
  - npm run check:examples
  - npm run codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache: yarn
notifications:
  email: never
  slack:
    rooms:
      - vega-js:eJe5JNgxfucTVcTMbeplKX3v
    on_success: never
    on_failure: always
cache:
  directories:
  - $HOME/.yarn-cache
